# -*- coding: utf-8 -*-
"""finalODev.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FlclSJlPIPTe0mRjI1W5XjpTA_WHZFEv
"""

puan=0;
sorular={
    1:["Estonya'nın başkenti neresidir?","Tallin"],
    2:["Üçgenin iç açıları toplamı kaçtır?","180"],
    3:["7'nin küpü kaçtır?","343"],
    4:["Python'da birden fazla farklı değer tutabilen fakat aynı değerde sadece bir eleman tutan sırasız veri türü hangisidir?","set"],
    5:["i değişkeninin değerini 1 azaltmak için hangi ifade kullanılır?","i-- veya i-=i veya i=i-1"],
    6:["1 inch kaç cm'dir?","2.54"],
    7:["Türk alfabesinde kaç harf vardır?","29"],
    8:["Dünyada kaç kıta vardır?","7"],
    9:["Hangisi bilgisayarlarda kalıcı depolama birimidir?","HDD"],
    10:["İzmir'in plaka kodu kaçtır?","35"]
}
yanit1=input(sorular[1][0])
if(yanit1=="tallin" or yanit1.upper()=="TALLIN" or yanit1.capitalize()=="Tallin"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[1][1])

yanit2=input(sorular[2][0])
if(yanit2=="180"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[2][1])

yanit3=input(sorular[3][0])
if(yanit3=="343"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[3][1])

yanit4=input(sorular[4][0])
if(yanit4=="set" or yanit4.upper()=="SET" or yanit4.capitalize()=="Set"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[4][1])

yanit5=input(sorular[5][0])
if(yanit5=="i--" or yanit1=="i-=i" or yanit5=="i=i-1"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[5][1])

yanit6=input(sorular[6][0])
if(yanit6=="2.54" or yanit6=="2,54"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[6][1])

yanit7=input(sorular[7][0])
if(yanit7=="29"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[7][1])

yanit8=input(sorular[8][0])
if(yanit8=="7"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[8][1])

yanit9=input(sorular[9][0])
if(yanit9=="hdd" or yanit9.upper()=="HDD" or yanit9.capitalize()=="Hdd"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[9][1])

yanit10=input(sorular[10][0])
if(yanit10=="35"):
  puan+=10
  print("Tebrikler. Doğru.")
else:
  print("Üzgünüm. Yanlış.Doğru yanıt",sorular[10][1])


if(puan<=50):
  print("Üzgünüm. Başarısız oldunuz. Puanınız: ", puan)
else:
  print("Kutlarız. Başardınız. Puanınız: ", puan)