# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JfNZXmV4_6NvTp2kfH3CsynJYqAJ4dYq
"""

list1=[1,3,5,7,9]
list2=[2,4,6,8]
for x in list1+list2:
  x=x*2
  print(type(x))