# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JfNZXmV4_6NvTp2kfH3CsynJYqAJ4dYq
"""

print("hello")

D={1:1, 2:'2', '1':2, '2':3}
D['1']=2
print(D[D[D[str(D[1])]]])

l=[x if x%2 else x*100 for x in range(1,5)]
print(l)

list1=[1,3,5,7,9]
list2=[2,4,6,8]
for x in list1+list2:
  x=x*2
  print(type(x))