# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMqstO8xMci9CkrFCDHPebF4B2V0C6Th
"""

dict1={"name":"ali",
       "age":23,
       "dept":"IT"
       }
dict2={"name":"veli",
       "age":24,
       "dept":"IT"}
dict3={"name":"ayşe",
       "age":22,
       "dept":"IK"}
dict4={"name":"cem",
       "age":28,
       "dept":"Muhasebe"}
dict5={"name":"buse",
       "age":29,
       "dept":"IK"}

print(dict1.items())
print(dict2.items())
print(dict3.items())
print(dict4.items())
print(dict5.items())