# -*- coding: utf-8 -*-
"""hw3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aU9OHtF2CPpbmw0SUXU0FiQuNnqKtuWo
"""

st1MidTerm=int(input("St1:Your MidTerm Grade:"))
st1Project=int(input("St1:Your Project Grade:"))
st1Final=int(input("St1:Your Final Grade:"))
student1PassingGrade=(st1MidTerm*0.3) + (st1Project*0.3) + (st1Final*0.4)
st1={"name":"st1", 
     "st1MidTerm":st1MidTerm,
     "st1Project":st1Project,
     "st1Final":st1Final,
     "student1PassingGrade":student1PassingGrade
     }

st2MidTerm=int(input("St2:Your MidTerm Grade:"))
st2Project=int(input("St2:Your Project Grade:"))
st2Final=int(input("St2:Your Final Grade:"))
student2PassingGrade=(st2MidTerm*0.3) + (st2Project*0.3) + (st2Final*0.4)
st2={"name":"st2", 
     "st2MidTerm":st2MidTerm,
     "st2Project":st2Project,
     "st2Final":st2Final,
     "student2PassingGrade":student2PassingGrade
     }

st3MidTerm=int(input("St3:Your MidTerm Grade:"))
st3Project=int(input("St3:Your Project Grade:"))
st3Final=int(input("St3:Your Final Grade:"))
student3PassingGrade=(st3MidTerm*0.3) + (st3Project*0.3) + (st3Final*0.4)
st3={"name":"st3", 
     "st3MidTerm":st3MidTerm,
     "st3Project":st3Project,
     "st3Final":st3Final,
     "student3PassingGrade":student3PassingGrade
     }


st4MidTerm=int(input("St4:Your MidTerm Grade:"))
st4Project=int(input("St4:Your Project Grade:"))
st4Final=int(input("St4:Your Final Grade:"))
student4PassingGrade=(st4MidTerm*0.3) + (st4Project*0.3) + (st4Final*0.4)
st4={"name":"st4", 
     "st4MidTerm":st4MidTerm,
     "st4Project":st4Project,
     "st4Final":st4Final,
     "student4PassingGrade":student4PassingGrade
     }


st5MidTerm=int(input("St5:Your MidTerm Grade:"))
st5Project=int(input("St5:Your Project Grade:"))
st5Final=int(input("St5:Your Final Grade:"))
student5PassingGrade=(st5MidTerm*0.3) + (st5Project*0.3) + (st5Final*0.4)
st5={"name":"st5", 
     "st5MidTerm":st5MidTerm,
     "st5Project":st5Project,
     "st5Final":st5Final,
     "student5PassingGrade":student5PassingGrade
     }

st1Grade=st1["student1PassingGrade"]
st2Grade=st2["student2PassingGrade"]
st3Grade=st3["student3PassingGrade"]
st4Grade=st4["student4PassingGrade"]
st5Grade=st5["student5PassingGrade"]

PassingGradesofStudents=[st1Grade,st2Grade,st3Grade,st4Grade,st5Grade]
PassingGradesofStudents.sort(reverse=True)
print(PassingGradesofStudents)